//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int Id_user { get; set; }
        public string Name_user { get; set; }
        public string Login_user { get; set; }
        public string Password_user { get; set; }
    }
}
